accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name = 'signin'),
    path('signup/', views.signup, name = 'signup'),
    path('signout/', views.signout, name = 'signout'),
    path('find_username/', views.find_username, name = 'find_username'),
]

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="main"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('qna/', include('qna.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # 미디어 파일
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('<int:product_id>/', views.product_detail, name='detail'),
    path('<int:product_id>/question/create/', views.question_create, name='question_create'),
    path('<int:product_id>/question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    path('<int:product_id>/question/modify/<int:question_id>', views.question_modify, name='question_modify'),
]

qna/urls.py
app_name = 'qna'

urlpatterns = [

]

products/models.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

# Create your models here.
from markets.models import Market
from qna.models import Question


class Product(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    is_deleted = models.BooleanField('삭제여부', default=False)
    delete_date = models.DateTimeField('삭제날짜', null=True, blank=True)
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)
    name = models.CharField('상품명(내부용)', max_length=100)
    display_name = models.CharField('상품명(고객용)', max_length=100)
    price = models.PositiveIntegerField('권장판매가')
    sale_price = models.PositiveIntegerField('실제판매가')
    is_hidden = models.BooleanField('노출여부', default=False)
    is_sold_out = models.BooleanField('품절여부', default=False)
    category_id = models.PositiveIntegerField('카테고리번호(추후설계)', default=0)
    hit_count = models.PositiveIntegerField('조회수', default=0)
    review_count = models.PositiveIntegerField('리뷰수', default=0)
    review_point = models.PositiveIntegerField('리뷰평점', default=0)
    questions = GenericRelation(Question, related_query_name="question")

    def thumb_img_url(self):
        return f"https://picsum.photos/id/{self.id}/300/300"

class ProductReal(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_reals")
    option_1_type = models.CharField('옵션1 타입', max_length=10, default='SIZE')
    option_1_name = models.CharField('옵션1 이름(내부용)', max_length=50)
    option_1_display_name = models.CharField('옵션1 이름(고객용)', max_length=50)
    option_2_type = models.CharField('옵션2 타입', max_length=10, default='COLOR')
    option_2_name = models.CharField('옵션2 이름(내부용)', max_length=50)
    option_2_display_name = models.CharField('옵션2 이름(고객용)', max_length=50)
    option_3_type = models.CharField('옵션3 타입', max_length=10, default='', blank=True)
    option_3_name = models.CharField('옵션3 이름(내부용)', max_length=50, default='', blank=True)
    option_3_display_name = models.CharField('옵션3 이름(고객용)', max_length=50, default='', blank=True)
    is_sold_out = models.BooleanField('품절여부', default=False)
    is_hidden = models.BooleanField('노출여부', default=False)
    add_price = models.IntegerField('추가가격', default=0)
    stock_quantity = models.PositiveIntegerField('재고개수', default=0)  # 품절일때 유용함

products/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core import exceptions
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect

from products.models import Product
from qna.forms import QuestionForm
from qna.models import Question


def product_list(request: HttpRequest):
    products = Product.objects.order_by('-id')

    return render(request, "products/product_list.html", {
        "products": products
    })


def _product_detail(request: HttpRequest, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == "POST" and request.user.is_authenticated:
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.content_type = ContentType.objects.get_for_model(product)
            question.object_id = product.id
            question.user = request.user
            question.save()
            messages.success(request, "질문이 등록되었습니다.")

            return redirect("products:detail", product_id=product.id)
    else:
        form = QuestionForm()

        form.errors

    product_reals = product.product_reals.order_by('option_1_display_name', 'option_2_display_name')
    questions = product.questions.order_by('-id')

    return render(request, "products/product_detail.html", {
        "product": product,
        "product_reals": product_reals,
        "questions": questions,
        "question_form": form
    })


def product_detail(request: HttpRequest, product_id):
    return _product_detail(request, product_id)


def question_create(request: HttpRequest, product_id):
    return _product_detail(request, product_id)


@login_required
def question_delete(request: HttpRequest, product_id, question_id):
    question = get_object_or_404(Question, id=question_id)

    if request.user != question.user:
        raise exceptions.PermissionDenied()

    question.delete()

    messages.success(request, "질문이 삭제되었습니다.")

    return redirect("products:detail", product_id=product_id)


def question_modify(request: HttpRequest, product_id, question_id):
    product = get_object_or_404(Product, id=product_id)
    question = get_object_or_404(Question, id=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            form.save()
            messages.success(request, "질문이 수정되었습니다.")
            return redirect("products:detail", product_id=product_id)
    else:
        form = QuestionForm(None, instance=question)

    return render(request, "products/question_modify.html", {
        "product": product,
        "question": question,
        "question_form": form,
    })

products/templates/products/product_detail.html
{% extends "layout.html" %}
{% load humanize %}
{% load django_bootstrap5 %}

{%block content %}

<section class="section-prod-detail">
    <div class="container">
        <div class="card">
            <div class="card-header">
                상품상세정보
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <img class="t-w-full t-max-w-[300px] t-rounded" src="{{product.thumb_img_url}}" alt="">
                </li>
                <li class="list-group-item">
                    번호 : <span class="badge bg-primary">{{product.id}}</span>
                </li>
                <li class="list-group-item">
                    등록날짜 : <span class="badge bg-secondary">{{product.reg_date}}</span>
                </li>
                <li class="list-group-item">
                    수정날짜 : <span class="badge bg-secondary">{{product.update_date}}</span>
                </li>
                <li class="list-group-item">
                    상품명 : <span class="t-font-bold">{{product.display_name}}</span>
                </li>
                <li class="list-group-item">
                    가격 : <span class="t-font-bold">{{product.sale_price|intcomma}}</span>원
                </li>
                <li class="list-group-item">
                    마켓 : <span class="badge bg-primary">{{product.market.name}}</span>
                </li>
            </ul>

        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                옵션
            </div>

            <ul class="list-group list-group-flush">
                {% for product_real in product_reals %}
                <li class="list-group-item">
                    {{product_real.option_1_type}} : <span class="badge bg-secondary">{{product_real.option_1_display_name}}</span>
                    /
                    {{product_real.option_2_type}} : <span class="badge bg-secondary">{{product_real.option_2_display_name}}</span>
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                질문등록
            </div>

            <div class="card-body">
                {% if user.is_authenticated %}

                <form method="POST" action="{% url 'products:question_create' product.id %}">
                    {% csrf_token %}

                    {% bootstrap_form question_form %}
                    {% bootstrap_button button_type="submit" content="질문작성" %}
                    {% bootstrap_button button_type="reset" content="취소" %}

                </form>
                {% else %}
                <a href="{% url 'accounts:signin' %}?next={{request.get_full_path}}">로그인</a> 후 이용해주세요.
                {% endif %}

                {% if question_form.errors %}
                <script>
                    let $lastForm = $('form').last();
                    $(window).on('load', function() {
                        $(window).scrollTop($lastForm.offset().top);
                    });


                </script>
                {% endif %}

            </div>
        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                질문리스트
            </div>

            <ul class="list-group list-group-flush">
                {% for question in questions %}
                <li class="list-group-item">
                    <span class="badge bg-secondary">{{question.id}}</span>
                    {{question.body}}
                    {% if question.user == request.user %}
                    <a href="{% url 'products:question_delete' product.id question.id %}" class="btn btn-sm btn-warning"
                       onclick="if ( confirm('정말 삭제하시겠습니까?') == false ) return false;">삭제</a>
                    {% endif %}
                    <a href="{% url 'products:question_modify' product.id question.id %}"
                       class="btn btn-sm btn-secondary">수정</a>
                </li>
                {% endfor %}
            </ul>
        </div>

    </div>
</section>
{%endblock%}

products/templates/products/product_list.html
{% extends "layout.html" %}
{% load humanize %}

{%block content %}
{% with img_box_class="t-relative t-overflow-hidden t-rounded" %}
{% with img_box_before_class="before:t-content-[''] before:t-absolute before:t-inset-0 before:t-bg-[#00000000] group-hover:before:t-bg-[#00000055] before:t-transition-all" %}
{% with img_box_after_class="after:t-content-[attr(data-before)] after:t-hidden group-hover:after:t-block after:t-no-underline after:t-text-white after:t-border-2 after:t-border-white after:t-border-solid after:t-rounded after:t-p-2 after:t-whitespace-nowrap after:t-absolute after:t-top-[50%] after:t-left-[50%] after:t-translate-y-[-50%] after:t-translate-x-[-50%] after:t-transition-all" %}

<section class="section-prod-list">
    <div class="container">
        <h1 class="t-text-[1.2rem] t-font-bold">최신 상품리스트</h1>

        <ul class="t-grid t-grid-cols-1 sm:t-grid-cols-2 md:t-grid-cols-3 lg:sm:t-grid-cols-4 t-gap-[20px] t-mt-3">
            {% for product in products %}
            <li class="t-flex t-flex-col t-group">
                <a data-before="VIEW MORE" href="{% url 'products:detail' product.id %}"
                   class="{{img_box_class}} {{img_box_before_class}} {{img_box_after_class}}">
                    <img class="t-block t-w-full t-transition-all group-hover:t-scale-110 t-relative t--z-50"
                         src="{{product.thumb_img_url}}" alt="">
                </a>
                <a class="t-text-center t-mt-2 t-no-underline t-text-black t-italic group-hover:t-underline"
                   href="{% url 'products:detail' product.id %}">
                    {{product.display_name}}
                </a>
                <a class="t-text-center t-mt-2 t-no-underline t-text-gray-400 group-hover:t-text-blue-500"
                   href="{% url 'products:detail' product.id %}">
                    <i class="fas fa-won-sign"></i>
                    <span>{{ product.sale_price|intcomma }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endwith %}
{% endwith %}
{% endwith %}

{%endblock%}

products/templates/products/question_modify.html
{% extends "layout.html" %}
{% load humanize %}
{% load django_bootstrap5 %}

{%block content %}

<section class="section-prod-question-modify">
    <div class="container">
        <div class="card">
            <div class="card-header">
                상품상세정보
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <img class="t-w-full t-max-w-[300px]" src="{{product.thumb_img_url}}" alt="">
                </li>
                <li class="list-group-item">
                    번호 : <span class="badge bg-primary">{{product.id}}</span>
                </li>
                <li class="list-group-item">
                    등록날짜 : <span class="badge bg-secondary">{{product.reg_date}}</span>
                </li>
                <li class="list-group-item">
                    수정날짜 : <span class="badge bg-secondary">{{product.update_date}}</span>
                </li>
                <li class="list-group-item">
                    상품명 : <span class="t-font-bold">{{product.display_name}}</span>
                </li>
                <li class="list-group-item">
                    가격 : <span class="t-font-bold">{{product.sale_price|intcomma}}</span>원
                </li>
                <li class="list-group-item">
                    마켓 : <span class="badge bg-primary">{{product.market.name}}</span>
                </li>
            </ul>

        </div>

        <div class="card t-mt-5">
            <div class="card-header">
                상품질문수정
            </div>

            <div class="card-body">
                <form method="POST" action="{% url 'products:question_modify' product.id question.id %}">
                    {% csrf_token %}

                    {% bootstrap_form question_form %}
                    {% bootstrap_button button_type="submit" content="질문수정" %}
                    {% bootstrap_button button_type="reset" content="취소" %}

                </form>
                <script>
                    let $lastForm = $('form').last();
                    $(window).on('load', function() {
                        $(window).scrollTop($lastForm.offset().top);
                    });
                </script>
            </div>

        </div>

    </div>
</section>
{%endblock%}